In [13]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[1]

In [14]:
file_path = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "accounts_userquestionrecord_preprocessed.csv"
)

question_df = pd.read_csv(file_path)

print("원본 shape:", question_df.shape)
question_df.head()

원본 shape: (1217558, 12)

,id,status,created_at,chosen_user_id,question_id,user_id,question_piece_id,has_read,answer_status,answer_updated_at,report_count,opened_times
0,771777,C,2023-04-28 12:27:49,849469,252,849436,998458,0,N,2023-04-28 12:27:49,0,0
1,771800,C,2023-04-28 12:28:02,849446,244,849436,998459,0,N,2023-04-28 12:28:02,0,0
2,771812,C,2023-04-28 12:28:09,849454,183,849436,998460,1,N,2023-04-28 12:28:09,0,0
3,771828,C,2023-04-28 12:28:16,847375,101,849436,998461,0,N,2023-04-28 12:28:16,0,0
4,771851,C,2023-04-28 12:28:26,849477,209,849436,998462,1,N,2023-04-28 12:28:26,0,0

In [15]:
question_df["created_at"] = pd.to_datetime(
    question_df["created_at"],
    errors="coerce"
)

start_date = pd.Timestamp("2023-05-13")
end_date = pd.Timestamp("2024-05-08")  # 5/7 23:59:59까지 포함하기 위해

question_period = question_df[
    (question_df["created_at"] >= start_date) &
    (question_df["created_at"] < end_date)
].copy()

print("기간 필터 전:", question_df.shape)
print("기간 필터 후:", question_period.shape)

print(
    question_period["created_at"].min(),
    "~",
    question_period["created_at"].max()
)

기간 필터 전: (1217558, 12)
기간 필터 후: (800793, 12)
2023-05-13 00:00:02 ~ 2024-05-07 11:29:07

In [16]:
question_analysis = question_period[
    question_period["chosen_user_id"].notna()
].copy()

print("최종 shape:", question_analysis.shape)
print(
    "선택받은 고유 사용자 수:",
    question_analysis["chosen_user_id"].nunique()
)

최종 shape: (800793, 12)
선택받은 고유 사용자 수: 13811

In [17]:
output_path = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "accounts_userquestionrecord_preprocessed_2.csv"
)

question_analysis.to_csv(output_path, index=False)

print("저장 완료:", output_path)

저장 완료: /Users/jsun99/Workspace/02_develop/projects/team4-final-project/data/interim/accounts_userquestionrecord_preprocessed_2.csv

---

In [18]:
file_path = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "polls_questionpiece_preprocessed.csv"
)

piece_df = pd.read_csv(file_path)

print("원본 shape:", piece_df.shape)
piece_df.head()

원본 shape: (1264349, 5)

       id  is_voted           created_at  question_id  is_skipped
0  998458         1  2023-04-28 12:27:22          252           0
1  998459         1  2023-04-28 12:27:22          244           0
2  998460         1  2023-04-28 12:27:22          183           0
3  998461         1  2023-04-28 12:27:22          101           0
4  998462         1  2023-04-28 12:27:22          209           0

In [19]:
piece_df["created_at"] = pd.to_datetime(
    piece_df["created_at"],
    errors="coerce"
)

start_date = pd.Timestamp("2023-05-13")
end_date = pd.Timestamp("2024-05-08")

piece_analysis = piece_df[
    (piece_df["created_at"] >= start_date) &
    (piece_df["created_at"] < end_date)
].copy()

print("기간 필터 전:", piece_df.shape)
print("기간 필터 후:", piece_analysis.shape)

print(
    piece_analysis["created_at"].min(),
    "~",
    piece_analysis["created_at"].max()
)

기간 필터 전: (1264349, 5)
기간 필터 후: (823739, 5)
2023-05-13 00:00:04 ~ 2024-05-07 11:32:30

In [20]:
output_path = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "polls_questionpiece_preprocessed_2.csv"
)

piece_analysis.to_csv(output_path, index=False)

print("저장 완료:", output_path)
print("최종 shape:", piece_analysis.shape)

저장 완료: /Users/jsun99/Workspace/02_develop/projects/team4-final-project/data/interim/polls_questionpiece_preprocessed_2.csv
최종 shape: (823739, 5)

---

In [21]:
file_path = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "accounts_pointhistory_preprocessed.csv"
)

point_df = pd.read_csv(file_path)

print("원본 shape:", point_df.shape)
point_df.head()

원본 shape: (2338918, 5)

       id  delta_point           created_at  user_id  user_question_record_id
0  790629            9  2023-04-28 12:27:49   849436                 771777.0
1  790652            9  2023-04-28 12:28:02   849436                 771800.0
2  790664            5  2023-04-28 12:28:09   849436                 771812.0
3  790680           13  2023-04-28 12:28:16   849436                 771828.0
4  790703            5  2023-04-28 12:28:26   849436                 771851.0

In [22]:
point_df["created_at"] = pd.to_datetime(
    point_df["created_at"],
    errors="coerce"
)

start_date = pd.Timestamp("2023-05-13")
end_date = pd.Timestamp("2024-05-08")

point_analysis = point_df[
    (point_df["created_at"] >= start_date) &
    (point_df["created_at"] < end_date) &
    (point_df["delta_point"] < 0)
].copy()

print("필터 전:", point_df.shape)
print("필터 후:", point_analysis.shape)

print(
    point_analysis["created_at"].min(),
    "~",
    point_analysis["created_at"].max()
)

print(
    "포인트 소모 사용자 수:",
    point_analysis["user_id"].nunique()
)

필터 전: (2338918, 5)
필터 후: (88762, 5)
2023-05-13 00:00:44 ~ 2024-05-07 11:01:05
포인트 소모 사용자 수: 4021

In [23]:
point_analysis["delta_point"].value_counts().sort_index()

delta_point
-1000     1422
-500      6147
-300     20445
-200     20781
-30          1
-10      39966
Name: count, dtype: int64

In [24]:
print(
    point_analysis["delta_point"]
    .value_counts()
    .head(20)
)

delta_point
-10      39966
-200     20781
-300     20445
-500      6147
-1000     1422
-30          1
Name: count, dtype: int64

In [25]:
output_path = (
    PROJECT_ROOT
    / "data"
    / "interim"
    / "accounts_pointhistory_preprocessed_2.csv"
)

point_analysis.to_csv(output_path, index=False)

print("저장 완료:", output_path)
print("최종 shape:", point_analysis.shape)

저장 완료: /Users/jsun99/Workspace/02_develop/projects/team4-final-project/data/interim/accounts_pointhistory_preprocessed_2.csv
최종 shape: (88762, 5)