# account_userquestionrecord 테이블 전처리

In [ ]:
import pandas as pd

In [ ]:
file_path = 'C:/Users/andan/OneDrive/바탕 화면/accounts_userquestionrecord.csv' # 파일 경로는 각자 설정해주시면 될 것 같습니다.

df = pd.read_csv(file_path, header=None, encoding='euc-kr')

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,771777,C,2023-04-28 12:27:49,849469,252,849436,998458,0,N,2023-04-28 12:27:49,0,0
1,771800,C,2023-04-28 12:28:02,849446,244,849436,998459,0,N,2023-04-28 12:28:02,0,0
2,771812,C,2023-04-28 12:28:09,849454,183,849436,998460,1,N,2023-04-28 12:28:09,0,0
3,771828,C,2023-04-28 12:28:16,847375,101,849436,998461,0,N,2023-04-28 12:28:16,0,0
4,771851,C,2023-04-28 12:28:26,849477,209,849436,998462,1,N,2023-04-28 12:28:26,0,0

MySQL에서 csv로 추출 -> 실패 -> 용량 때문임을 알게됨 -> cmd로 추출 -> 라벨링이 안되어 있음 -> 라벨링 작업

In [3]:
columns = [
    'id', 
    'status', 
    'created_at', 
    'chosen_user_id', 
    'question_id', 
    'user_id', 
    'question_piece_id', 
    'has_read', 
    'answer_status', 
    'answer_updated_at', 
    'report_count', 
    'opened_times'
]

df.columns = columns

df.head()

,id,status,created_at,chosen_user_id,question_id,user_id,question_piece_id,has_read,answer_status,answer_updated_at,report_count,opened_times
0,771777,C,2023-04-28 12:27:49,849469,252,849436,998458,0,N,2023-04-28 12:27:49,0,0
1,771800,C,2023-04-28 12:28:02,849446,244,849436,998459,0,N,2023-04-28 12:28:02,0,0
2,771812,C,2023-04-28 12:28:09,849454,183,849436,998460,1,N,2023-04-28 12:28:09,0,0
3,771828,C,2023-04-28 12:28:16,847375,101,849436,998461,0,N,2023-04-28 12:28:16,0,0
4,771851,C,2023-04-28 12:28:26,849477,209,849436,998462,1,N,2023-04-28 12:28:26,0,0

### 중복 제거

In [5]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

0

중복값 X

### 결측치 확인

In [6]:
df.isnull().sum()

id                   0
status               0
created_at           0
chosen_user_id       0
question_id          0
user_id              0
question_piece_id    0
has_read             0
answer_status        0
answer_updated_at    0
report_count         0
opened_times         0
dtype: int64

결측 X

### 이상치 확인

In [8]:
df.describe()

,id,chosen_user_id,question_id,user_id,question_piece_id,has_read,report_count,opened_times
count,1.217558e+06,1.217558e+06,1.217558e+06,1.217558e+06,1.217558e+06,1.217558e+06,1.217558e+06,1.217558e+06
mean,5.957298e+07,1.092604e+06,6.843895e+02,1.105790e+06,7.413211e+07,5.551530e-01,1.765830e-04,6.332511e-02
std,4.608193e+07,2.027585e+05,6.250399e+02,2.062704e+05,5.757237e+07,4.969490e-01,2.040530e-02,3.011468e-01
min,7.717770e+05,8.331120e+05,9.900000e+01,8.380230e+05,9.984580e+05,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.553965e+07,8.836920e+05,2.750000e+02,8.846190e+05,1.854142e+07,0.000000e+00,0.000000e+00,0.000000e+00
50%,5.302680e+07,1.091749e+06,4.690000e+02,1.117537e+06,6.616843e+07,1.000000e+00,0.000000e+00,0.000000e+00
75%,9.480960e+07,1.235698e+06,9.420000e+02,1.259186e+06,1.176735e+08,1.000000e+00,0.000000e+00,0.000000e+00
max,1.616665e+08,1.579422e+06,5.133000e+03,1.583358e+06,2.083515e+08,1.000000e+00,1.400000e+01,3.000000e+00

In [10]:
print("숫자형 데이터 기초 통계 (마이너스 값이나 비정상적인 최대값 확인) ---")
print(df[['report_count', 'opened_times']].describe())
print("\n")

print("상태(status) 종류별 개수 확인 ---")
print(df['status'].value_counts())
print("\n")

print("답장 상태(answer_status) 종류별 개수 확인 ---")
print(df['answer_status'].value_counts())

숫자형 데이터 기초 통계 (마이너스 값이나 비정상적인 최대값 확인) ---
       report_count  opened_times
count  1.217558e+06  1.217558e+06
mean   1.765830e-04  6.332511e-02
std    2.040530e-02  3.011468e-01
min    0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00
75%    0.000000e+00  0.000000e+00
max    1.400000e+01  3.000000e+00


상태(status) 종류별 개수 확인 ---
status
C    1156322
I      60578
B        658
Name: count, dtype: int64


답장 상태(answer_status) 종류별 개수 확인 ---
answer_status
N    1097932
A     111761
P       7865
Name: count, dtype: int64

문자열도 3개씩 정리되어있음
이상치로 보이는 것은 없음

### 파일 다운로드

In [11]:
save_path = 'C:/Users/andan/OneDrive/바탕 화면/accounts_userquestionrecord_전처리완료.csv'

df.to_csv(save_path, index=False, encoding='utf-8-sig')

print("작업 완료")

작업 완료